version: "3.7"

services:
  mysql-db:
    image: mysql:latest
    container_name: thymeleaf_mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysqladmin
      MYSQL_DATABASE: thymeleaf_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - thymeleaf-db-data:/var/lib/mysql
    restart: always

volumes:
  thymeleaf-db-data:
